num1 = int(input("Enter Num 1 : "))
num2 = int(input("Enter Num 2 :"))

print("+ : " , num1 + num2)
print("- : " , num1 - num2)
print("* : " , num1 * num2)
print("/ : " , num1 / num2)
print("// : " , num1 // num2)
print("** : " , num1 ** num2)
print("% : " , num1 % num2)
print("Hello World ")
print("Hello World")